version: '3.9'

services:

  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
      - 9502:9502
    depends_on:
      - hyperf-skeleton-mariadb
      - hyperf-skeleton-redis
    networks:
      - project_swoole

  hyperf-skeleton-nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - 443:443
    depends_on:
        - hyperf-skeleton
    volumes: 
        - /www/wwwroot
        - ./docker/nginx/:/etc/nginx/conf.d/
        - ./logs:/var/log/nginx
        - ./ssl_certificate:/ssl_certificate
    networks:
      - project_swoole
    
  hyperf-skeleton-mariadb:
    container_name: hyperf-skeleton-mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "hyperf-skeleton"
    networks:
      - project_swoole

  hyperf-skeleton-redis:
    container_name: hyperf-skeleton-redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - project_swoole
      
networks:
  project_swoole:
    driver: bridge